server:
  port: 9528
management:
  server:
    port: 9529
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  mail:
    host: ${SPRING_MAIL_HOST:smtp.163.com}
    port: ${SPRING_MAIL_PORT:465}
    username: ${SPRING_MAIL_USERNAME:xxx@163.com}
    password: ${SPRING_MAIL_PASSWORD:xxxx}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true

  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
    database: ${SPRING_REDIS_DATABASE:15}
    password: ${SPRING_REDIS_PASSWORD:}
    jedis:
      pool:
        # 资源池中最大连接数
        # 默认8，-1表示无限制；可根据服务并发redis情况及服务端的支持上限调整
        max-active: 8
        # 资源池运行最大空闲的连接数
        # 默认8，-1表示无限制；可根据服务并发redis情况及服务端的支持上限调整，一般建议和max-active保持一致，避免资源伸缩带来的开销
        max-idle: 50
        # 当资源池连接用尽后，调用者的最大等待时间(单位为毫秒)
        # 默认 -1 表示永不超时，设置5秒
        max-wait: 5000

azkaban:
  profile: ${AZKABAN_PROFILE:dev}
  host: ${AZKABAN_HOST:http://ip:port}
  username: ${AZKABAN_USERNAME:azkaban}
  password: ${AZKABAN_PASSWORD:azkaban}
  mailTemplatePath: /templates/
  mailSuccessFtl: success.ftl
  mailFailFtl: fail.ftl
  toMailArray:
    - ${SPRING_MAIL_USERNAME:xxx@163.com}
    - xxxx@qq.com
  monitorFlowMap:
    # 需要监控的任务流 格式 project: flow
    # 即execution_job表里的project_id对应的名称: execution_job表里的flow_id
    TEST: TEST